export const ECONOMY = {
  // Saldo inicial
  MOEDAS_INICIAIS: 50,
  BONUS_BOAS_VINDAS: 30,
  BONUS_AMIGO_CONVIDADO: 30,
  BONUS_QUEM_CONVIDOU: 30,
  LIMITE_CONVITES: 10,

  // XP por questão acertada (varia por dificuldade)
  XP_FACIL:   5,
  XP_MEDIO:   7,
  XP_DIFICIL: 9,

  // Ganhos por jogabilidade
  COMPLETAR_JOGO: 5,
  BONUS_PERFEITO: 10,
  STOP_CATEGORIA_VALIDA: 1,
  STOP_ONLINE_VITORIA: 20,
  STOP_ONLINE_VITORIA_ASSINCRONA: 15,
  STOP_ONLINE_EMPATE: 10,
  STOP_ONLINE_EMPATE_ASSINCRONO: 8,
  STOP_ONLINE_ADVERSARIO_ABANDONOU: 25,
  STOP_ONLINE_CATEGORIA_APROVADA: 10,
  PEREGRINACAO_SANTUARIO: 5,
  PEREGRINACAO_COMPLETA: 50,
  SOLITARIO_COMPLETAR: 5,
  SOLITARIO_BONUS_SEM_DICA: 3,
  SOLITARIO_BONUS_MOVIMENTOS: 2,

  // Anúncios e bônus
  ASSISTIR_ANUNCIO: 15,
  LIMITE_ANUNCIOS_DIA: 3,
  COOLDOWN_ANUNCIO_MINUTOS: 10,
  BONUS_2H: 5,
  COOLDOWN_BONUS_HORAS: 2,

  // Custos — dicas nos jogos
  SABEDORIA_REVELAR_LETRA: 3,
  SABEDORIA_REVELAR_PALAVRA: 10,
  PEREGRINACAO_DICA_DIRECAO: 5,
  PEREGRINACAO_DICA_TEXTO: 8,
  PEREGRINACAO_REVELAR_SANTUARIO: 20,
  PALAVRA_FE_REVELAR_LETRA: 5,
  DESAFIO_LITURGICO_TEMPO_EXTRA: 8,
  BOGGLE_REVELAR_LETRA: 5,
  BOGGLE_MAX_REVELACOES: 3,
  SOLITARIO_DESFAZER: 5,
  SOLITARIO_DICA: 10,

  // Custos — Stop Online
  STOP_TROCAR_CATEGORIA: 3,
  STOP_TROCAR_TODAS_CATEGORIAS: 15,
  STOP_DICA_CATEGORIA: 5,
  STOP_PENALIDADE_ABANDONO: 15,

  // Custos — outros
  IA_PERGUNTA: 15,
  CONTINUAR_APOS_GAME_OVER: 20,
} as const;
