import type { QuizQuestion } from '@/hooks/use-game-packs';

export const ALL_QUESTIONS: QuizQuestion[] = [
  // ── FÁCIL ───────────────────────────────────────────────────────────────────
  {
    topic: 'Maria',
    question: 'Quem é a mãe de Jesus Cristo?',
    options: ['Maria Madalena', 'Maria, a Virgem', 'Isabel', 'Ana'],
    correct: 1,
    difficulty: 'facil',
  },
  {
    topic: 'Bíblia',
    question: 'Qual é o primeiro livro da Bíblia?',
    options: ['Êxodo', 'Salmos', 'Gênesis', 'Mateus'],
    correct: 2,
    difficulty: 'facil',
  },
  {
    topic: 'Jesus',
    question: 'Em que cidade Jesus nasceu?',
    options: ['Nazaré', 'Jerusalém', 'Belém', 'Cafarnaum'],
    correct: 2,
    difficulty: 'facil',
  },
  {
    topic: 'Apóstolos',
    question: 'Quantos apóstolos Jesus escolheu?',
    options: ['7', '10', '12', '14'],
    correct: 2,
    difficulty: 'facil',
  },
  {
    topic: 'Apóstolos',
    question: 'Qual apóstolo negou Jesus três vezes antes do canto do galo?',
    options: ['João', 'Tiago', 'André', 'Pedro'],
    correct: 3,
    difficulty: 'facil',
  },
  {
    topic: 'Apóstolos',
    question: 'Qual apóstolo traiu Jesus por trinta moedas de prata?',
    options: ['Tomé', 'Judas Iscariotes', 'Simão', 'Felipe'],
    correct: 1,
    difficulty: 'facil',
  },
  {
    topic: 'Jesus',
    question: 'Qual foi o primeiro milagre de Jesus, segundo o Evangelho de João?',
    options: ['Multiplicação dos pães', 'Cura de um cego', 'Água transformada em vinho', 'Ressurreição de Lázaro'],
    correct: 2,
    difficulty: 'facil',
  },
  {
    topic: 'João Batista',
    question: 'Quem batizou Jesus no Rio Jordão?',
    options: ['São Pedro', 'São Paulo', 'João Batista', 'São José'],
    correct: 2,
    difficulty: 'facil',
  },
  {
    topic: 'Nossa Senhora Aparecida',
    question: 'Nossa Senhora Aparecida é padroeira de qual país?',
    options: ['Portugal', 'Argentina', 'México', 'Brasil'],
    correct: 3,
    difficulty: 'facil',
  },
  {
    topic: 'Bíblia',
    question: 'Quantos livros tem a Bíblia Católica?',
    options: ['66', '73', '72', '80'],
    correct: 1,
    difficulty: 'facil',
  },
  {
    topic: 'Sacramentos',
    question: 'Qual é o primeiro sacramento que um cristão recebe?',
    options: ['Eucaristia', 'Crisma', 'Batismo', 'Confissão'],
    correct: 2,
    difficulty: 'facil',
  },
  {
    topic: 'São José',
    question: 'Qual era a profissão de São José, pai adotivo de Jesus?',
    options: ['Pescador', 'Comerciante', 'Carpinteiro', 'Pastor'],
    correct: 2,
    difficulty: 'facil',
  },
  {
    topic: 'Jesus',
    question: 'Em qual dia da semana Jesus ressuscitou?',
    options: ['Sexta-feira', 'Sábado', 'Domingo', 'Segunda-feira'],
    correct: 2,
    difficulty: 'facil',
  },
  {
    topic: 'São Paulo',
    question: 'Qual era o nome de São Paulo antes de sua conversão?',
    options: ['Simão', 'Barnabé', 'Saulo', 'Matias'],
    correct: 2,
    difficulty: 'facil',
  },
  {
    topic: 'Oração',
    question: 'Qual oração Jesus ensinou diretamente aos seus discípulos?',
    options: ['Ave Maria', 'Pai Nosso', 'Credo', 'Salve Rainha'],
    correct: 1,
    difficulty: 'facil',
  },
  // ── MÉDIO ───────────────────────────────────────────────────────────────────
  {
    topic: 'São Francisco de Assis',
    question: 'São Francisco de Assis fundou qual ordem religiosa?',
    options: ['Dominicanos', 'Jesuítas', 'Franciscanos', 'Beneditinos'],
    correct: 2,
    difficulty: 'medio',
  },
  {
    topic: 'Santa Teresa de Ávila',
    question: 'Santa Teresa de Ávila pertencia a qual ordem religiosa?',
    options: ['Franciscanas', 'Carmelitas', 'Dominicanas', 'Beneditinas'],
    correct: 1,
    difficulty: 'medio',
  },
  {
    topic: 'Doutrina',
    question: 'Qual é o significado da palavra "Eucaristia"?',
    options: ['Sacrifício Santo', 'Ação de Graças', 'Corpo de Cristo', 'Pão do Céu'],
    correct: 1,
    difficulty: 'medio',
  },
  {
    topic: 'São Tomás de Aquino',
    question: 'Quem escreveu a "Suma Teológica", obra fundamental da teologia católica?',
    options: ['Santo Agostinho', 'São Boaventura', 'São Tomás de Aquino', 'São Bernardo'],
    correct: 2,
    difficulty: 'medio',
  },
  {
    topic: 'São Domingos',
    question: 'São Domingos de Gusmão fundou qual ordem religiosa?',
    options: ['Franciscanos', 'Jesuítas', 'Dominicanos', 'Carmelitas'],
    correct: 2,
    difficulty: 'medio',
  },
  {
    topic: 'Fátima',
    question: 'Em que ano ocorreram as aparições de Nossa Senhora em Fátima, Portugal?',
    options: ['1910', '1917', '1920', '1929'],
    correct: 1,
    difficulty: 'medio',
  },
  {
    topic: 'Sacramentos',
    question: 'Qual sacramento fortalece a fé e une o cristão à Igreja através do Espírito Santo?',
    options: ['Eucaristia', 'Ordem', 'Matrimônio', 'Crisma'],
    correct: 3,
    difficulty: 'medio',
  },
  {
    topic: 'Liturgia',
    question: 'O "Advento" é o período litúrgico preparatório para qual festa?',
    options: ['Páscoa', 'Pentecostes', 'Natal', 'Corpus Christi'],
    correct: 2,
    difficulty: 'medio',
  },
  {
    topic: 'Bíblia',
    question: 'Quantos livros tem o Novo Testamento?',
    options: ['22', '25', '27', '39'],
    correct: 2,
    difficulty: 'medio',
  },
  {
    topic: 'São Pedro',
    question: 'Quem foi o primeiro papa da Igreja Católica?',
    options: ['São Paulo', 'São Pedro', 'São João', 'São Tiago'],
    correct: 1,
    difficulty: 'medio',
  },
  {
    topic: 'Doutrina',
    question: 'Qual sacramento apaga os pecados cometidos após o Batismo?',
    options: ['Eucaristia', 'Unção dos Enfermos', 'Confissão', 'Crisma'],
    correct: 2,
    difficulty: 'medio',
  },
  {
    topic: 'Nossa Senhora de Lourdes',
    question: 'Em qual cidade francesa apareceu Nossa Senhora a Santa Bernadette Soubirous?',
    options: ['Paris', 'Lyon', 'Lourdes', 'Versailles'],
    correct: 2,
    difficulty: 'medio',
  },
  {
    topic: 'São João Bosco',
    question: 'São João Bosco é o patrono de qual grupo?',
    options: ['Sacerdotes', 'Pescadores', 'Jovens', 'Enfermos'],
    correct: 2,
    difficulty: 'medio',
  },
  {
    topic: 'Doutrina',
    question: 'Qual dogma proclamado em 1854 afirma que Maria foi concebida sem pecado original?',
    options: ['Assunção de Maria', 'Imaculada Conceição', 'Maternidade Divina', 'Perpétua Virgindade'],
    correct: 1,
    difficulty: 'medio',
  },
  {
    topic: 'São Nicolau',
    question: 'São Nicolau de Bari inspirou qual personagem popular do Natal?',
    options: ['Os Reis Magos', 'São Valentim', 'Papai Noel', 'Anjo do Natal'],
    correct: 2,
    difficulty: 'medio',
  },
  // ── DIFÍCIL ─────────────────────────────────────────────────────────────────
  {
    topic: 'Concílio de Niceia',
    question: 'Qual Concílio (325 d.C.) combateu o arianismo definindo que o Filho é "da mesma substância" que o Pai?',
    options: ['Concílio de Éfeso', 'Concílio de Calcedônia', 'Concílio de Niceia I', 'Concílio de Constantinopla I'],
    correct: 2,
    difficulty: 'dificil',
  },
  {
    topic: 'Santo Agostinho',
    question: 'Quem escreveu as "Confissões" e "A Cidade de Deus", pilares da patrística ocidental?',
    options: ['São Jerônimo', 'Santo Agostinho', 'São Gregório Magno', 'Tertuliano'],
    correct: 1,
    difficulty: 'dificil',
  },
  {
    topic: 'Grande Cisma',
    question: 'Em que ano ocorreu o Grande Cisma que dividiu a Igreja em Católica Romana e Ortodoxa Oriental?',
    options: ['1054', '1095', '1215', '1309'],
    correct: 0,
    difficulty: 'dificil',
  },
  {
    topic: 'Heresias',
    question: 'Qual heresia, condenada pelo Concílio de Niceia, negava a plena divindade de Cristo?',
    options: ['Gnosticismo', 'Arianismo', 'Pelagianismo', 'Nestorianismo'],
    correct: 1,
    difficulty: 'dificil',
  },
  {
    topic: 'São Tomás de Aquino',
    question: 'São Tomás de Aquino pertencia a qual ordem religiosa?',
    options: ['Franciscanos', 'Jesuítas', 'Dominicanos', 'Beneditinos'],
    correct: 2,
    difficulty: 'dificil',
  },
  {
    topic: 'Concílio Vaticano II',
    question: 'Em que anos foi realizado o Concílio Vaticano II, convocado por João XXIII?',
    options: ['1950–1958', '1958–1962', '1962–1965', '1965–1970'],
    correct: 2,
    difficulty: 'dificil',
  },
  {
    topic: 'Santa Catarina de Siena',
    question: 'Santa Catarina de Siena convenceu qual papa a retornar de Avignon para Roma?',
    options: ['Clemente VI', 'Inocêncio VI', 'Gregório XI', 'Urbano VI'],
    correct: 2,
    difficulty: 'dificil',
  },
  {
    topic: 'Bíblia',
    question: 'Quantos livros deuterocanônicos a Bíblia Católica possui (ausentes no cânon protestante)?',
    options: ['5', '6', '7', '9'],
    correct: 2,
    difficulty: 'dificil',
  },
  {
    topic: 'Mártires',
    question: 'Quem foi o primeiro mártir cristão, apedrejado por pregar o Evangelho em Jerusalém?',
    options: ['São Pedro', 'Santo Estêvão', 'São Tiago', 'São João'],
    correct: 1,
    difficulty: 'dificil',
  },
  {
    topic: 'Concílio de Calcedônia',
    question: 'O Concílio de Calcedônia (451 d.C.) definiu que Cristo possui quantas naturezas em uma única Pessoa?',
    options: ['Uma (divina)', 'Uma (humano-divina mista)', 'Duas (divina e humana)', 'Três'],
    correct: 2,
    difficulty: 'dificil',
  },
  {
    topic: 'São Inácio de Loyola',
    question: 'São Inácio de Loyola fundou qual ordem, conhecida por missões, educação e pelo lema "Ad Majorem Dei Gloriam"?',
    options: ['Dominicanos', 'Franciscanos', 'Companhia de Jesus (Jesuítas)', 'Carmelitas Descalços'],
    correct: 2,
    difficulty: 'dificil',
  },
  {
    topic: 'Doutrina',
    question: 'O "Filioque" — polêmico no Cisma de 1054 — afirma que o Espírito Santo procede do Pai e de quem?',
    options: ['Da Igreja', 'De Maria', 'Do Filho', 'Dos Apóstolos'],
    correct: 2,
    difficulty: 'dificil',
  },
  {
    topic: 'Doutrina Social',
    question: 'Qual encíclica do Papa Leão XIII (1891) é considerada o marco fundador da Doutrina Social da Igreja?',
    options: ['Rerum Novarum', 'Humanae Vitae', 'Evangelii Gaudium', 'Laudato Si'],
    correct: 0,
    difficulty: 'dificil',
  },
  {
    topic: 'Santa Teresa de Lisieux',
    question: 'Santa Teresa do Menino Jesus ficou conhecida por qual "caminho espiritual"?',
    options: ['Via da Contemplação Mística', 'Pequeno Caminho da Infância Espiritual', 'Caminho da Mortificação', 'Via Negativa'],
    correct: 1,
    difficulty: 'dificil',
  },
  {
    topic: 'São João Paulo II',
    question: 'João Paulo II (1978) foi o primeiro papa não italiano em quantos anos?',
    options: ['100 anos', '250 anos', '455 anos', '600 anos'],
    correct: 2,
    difficulty: 'dificil',
  },
];
